version: "3.5"

services:
  grafana:
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    platform: 'linux/amd64'
    container_name: 'grafana-connector-grafana'
    volumes:
      - ./dist:/var/lib/grafana/plugins/akenza-grafana-connector
      - ./provisioning:/etc/grafana/provisioning
    env_file:
      - config/grafana/grafana.config
    ports:
      - 3000:3000/tcp
    environment:
        GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "akenza-datasource"
